
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class VistaMenu extends javax.swing.JFrame {
    private Tienda tienda;
    private SistemaPago pago;
    private int nextPersonId;
    private int nextVentaId;
    private JTable tablaClientes;
    private JTable tablaEmpleados;
    private DefaultTableModel modeloTabla;
    private DefaultTableModel modeloEmpleados;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenu.class.getName());

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
        inicializarTablaClientes();
        inicializarTablaEmpleados();
        tienda = new Tienda(1, "Maxi Tienda", "Popayán");
    pago = new SistemaPago();
    nextPersonId = 1;
    nextVentaId = 1;
    this.setSize(600, 500); // ✅ Aumentar tamaño para la tabla
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Tienda");
        cargarDatosExistentesEnTabla();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarCliente = new javax.swing.JButton();
        RegistrarEmpleado = new javax.swing.JButton();
        RegistrarProducto = new javax.swing.JButton();
        CrearVenta = new javax.swing.JButton();
        MostrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrarCliente.setBackground(new java.awt.Color(153, 153, 153));
        RegistrarCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        RegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarCliente.setText("Registrar Cliente");
        RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClienteActionPerformed(evt);
            }
        });

        RegistrarEmpleado.setBackground(new java.awt.Color(153, 153, 153));
        RegistrarEmpleado.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        RegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarEmpleado.setText("Registrar Empleado");
        RegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEmpleadoActionPerformed(evt);
            }
        });

        RegistrarProducto.setBackground(new java.awt.Color(153, 153, 153));
        RegistrarProducto.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        RegistrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarProducto.setText("Registrar Producto");
        RegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProductoActionPerformed(evt);
            }
        });

        CrearVenta.setBackground(new java.awt.Color(153, 153, 153));
        CrearVenta.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        CrearVenta.setForeground(new java.awt.Color(255, 255, 255));
        CrearVenta.setText("Crear Venta");
        CrearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearVentaActionPerformed(evt);
            }
        });

        MostrarDatos.setBackground(new java.awt.Color(153, 153, 153));
        MostrarDatos.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        MostrarDatos.setForeground(new java.awt.Color(255, 255, 255));
        MostrarDatos.setText("Mostrar Datos");
        MostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addComponent(RegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MostrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrearVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClienteActionPerformed
        registrarCliente();
    }//GEN-LAST:event_RegistrarClienteActionPerformed

    private void RegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEmpleadoActionPerformed
        registrarEmpleado();
    }//GEN-LAST:event_RegistrarEmpleadoActionPerformed

    private void RegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProductoActionPerformed
        registrarProducto();
    }//GEN-LAST:event_RegistrarProductoActionPerformed

    private void CrearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearVentaActionPerformed
        crearVenta();
    }//GEN-LAST:event_CrearVentaActionPerformed

    private void MostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarDatosActionPerformed
        mostrarDatos();
    }//GEN-LAST:event_MostrarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaMenu().setVisible(true));
    }
private void registrarCliente() {
    try {
        String nombre = JOptionPane.showInputDialog(this, "Nombre del cliente:");
        if (nombre == null) return;
        String cedula = JOptionPane.showInputDialog(this, "Cedula:");
        if (cedula == null) return;
        String telefono = JOptionPane.showInputDialog(this, "Telefono:");
        if (telefono == null) return;

        Cliente c = new Cliente(nextPersonId++, nombre, cedula, telefono);
        tienda.getEmpleados(); // no-op: just ensure tienda exists
        JOptionPane.showMessageDialog(this, "Cliente registrado: " + c.getNombre());
        
        ClientRegistry.addCliente(c);
        agregarClienteATabla(c); // ✅ AGREGAR CLIENTE A LA TABLA
        
    } catch (HeadlessException ex) {
        JOptionPane.showMessageDialog(this, "Error al registrar cliente: " + ex.getMessage());
    }
}
private void registrarEmpleado() { 
    try {
        String nombre = JOptionPane.showInputDialog(this, "Nombre del empleado:");
        if (nombre == null) return;
        String cedula = JOptionPane.showInputDialog(this, "Cedula:");
        if (cedula == null) return;
        String telefono = JOptionPane.showInputDialog(this, "Telefono:");
        if (telefono == null) return;
        String cargo = JOptionPane.showInputDialog(this, "Cargo:");
        if (cargo == null) return;
        String sSalario = JOptionPane.showInputDialog(this, "Salario (numero):");
        if (sSalario == null) return;
        double salario = Double.parseDouble(sSalario);

        Empleado emp = new Empleado(nextPersonId++, nombre, cedula, telefono, cargo, salario);
        tienda.agregarEmpleado(emp);
        JOptionPane.showMessageDialog(this, "Empleado registrado: " + emp.getNombre());
        
        // ✅ AGREGAR ESTA LÍNEA PARA AÑADIR A LA TABLA
        agregarEmpleadoATabla(emp);
        
    } catch (HeadlessException | NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Error al registrar empleado: " + ex.getMessage());
    } 
}
    private void registrarProducto() {try {
            String codigo = JOptionPane.showInputDialog(this, "Codigo de barras del producto:");
            if (codigo == null) return;
            String nombre = JOptionPane.showInputDialog(this, "Nombre del producto:");
            if (nombre == null) return;
            String sPrecio = JOptionPane.showInputDialog(this, "Precio (numero):");
            if (sPrecio == null) return;
            double precio = Double.parseDouble(sPrecio);
            String sStock = JOptionPane.showInputDialog(this, "Stock (entero):");
            if (sStock == null) return;
            int stock = Integer.parseInt(sStock);

            Producto p = new Producto(codigo, nombre, precio, stock);
            tienda.agregarProducto(p);
            JOptionPane.showMessageDialog(this, "Producto registrado: " + p.getNombre());
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar producto: " + ex.getMessage());
        } }
    private void crearVenta() { try {
            if (ClientRegistry.getClientes().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay clientes registrados. Registre un cliente primero.");
                return;
            }
            
            String[] clientesArr = ClientRegistry.getClientes().stream().map(c -> c.getId() + ": " + c.getNombre()).toArray(String[]::new);
            String selCliente = (String) JOptionPane.showInputDialog(this, "Seleccione cliente:", "Cliente", JOptionPane.QUESTION_MESSAGE, null, clientesArr, clientesArr[0]);
            if (selCliente == null) return;
            int clientId = Integer.parseInt(selCliente.split(":")[0]);
            Cliente cliente = ClientRegistry.findById(clientId);

            
            Empleado empleado = null;
            if (!tienda.getEmpleados().isEmpty()) {
                String[] empArr = tienda.getEmpleados().stream().map(e -> e.getId() + ": " + e.getNombre()).toArray(String[]::new);
                String selEmp = (String) JOptionPane.showInputDialog(this, "Seleccione empleado (opcional):", "Empleado", JOptionPane.QUESTION_MESSAGE, null, empArr, empArr[0]);
                if (selEmp != null) {
                    int empId = Integer.parseInt(selEmp.split(":")[0]);
                    for (Empleado e : tienda.getEmpleados()) if (e.getId() == empId) { empleado = e; break; }
                }
            }

            Venta venta = new Venta(nextVentaId++, new Date(), cliente, empleado);

            
            while (true) {
                String codigo = JOptionPane.showInputDialog(this, "Ingrese codigo de producto (o cancelar para terminar):");
                if (codigo == null || codigo.trim().isEmpty()) break;
                Producto p = tienda.buscarProductoPorCodigo(codigo);
                if (p == null) { JOptionPane.showMessageDialog(this, "Producto no encontrado."); continue; }
                String sCant = JOptionPane.showInputDialog(this, "Cantidad:"); if (sCant == null) continue;
                int cant = Integer.parseInt(sCant);
                if (cant > p.getStock()) { JOptionPane.showMessageDialog(this, "Stock insuficiente. Stock actual: " + p.getStock()); continue; }

                venta.agregarItem(p, cant);
                p.actualizarStock(-cant);
                int option = JOptionPane.showConfirmDialog(this, "Agregar otro producto?", "Continuar", JOptionPane.YES_NO_OPTION);
                if (option != JOptionPane.YES_OPTION) break;
            }

            venta.calcularTotal();
            
            String medio = JOptionPane.showInputDialog(this, "Medio de pago (efectivo/tarjeta):");
        if (medio == null || medio.trim().isEmpty() || 
            (!medio.equalsIgnoreCase("efectivo") && !medio.equalsIgnoreCase("tarjeta"))) {
            JOptionPane.showMessageDialog(this, "Medio de pago no válido. Use 'efectivo' o 'tarjeta'");
            return;
        }

        boolean ok = Pago.procesarPago(venta.getTotal(), medio);
        if (ok) {
            tienda.registrarVenta(venta);
            JOptionPane.showMessageDialog(this, "Venta registrada. Total: " + venta.getTotal());
        } else {
            JOptionPane.showMessageDialog(this, "Pago fallido. Venta cancelada.");
        }
    } catch (HeadlessException | NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Error al crear venta: " + ex.getMessage());
    }
}
   private void mostrarDatos() {
    // Crear un panel con pestañas
    javax.swing.JTabbedPane tabbedPane = new javax.swing.JTabbedPane();
    
    // Pestaña de Clientes con tabla
    JScrollPane scrollClientes = new JScrollPane(tablaClientes);
    scrollClientes.setPreferredSize(new Dimension(500, 300));
    tabbedPane.addTab("Clientes", scrollClientes);
    
    // ✅ Pestaña de Empleados CON TABLA (no texto)
    JScrollPane scrollEmpleados = new JScrollPane(tablaEmpleados);
    scrollEmpleados.setPreferredSize(new Dimension(500, 300));
    tabbedPane.addTab("Empleados", scrollEmpleados);
    
    // Pestaña de Productos (texto)
    StringBuilder sbProductos = new StringBuilder();
    sbProductos.append("PRODUCTOS:\n");
    for (Producto p : tienda.getProductos()) 
        sbProductos.append(p.toString()).append("\n");
    JTextArea areaProductos = new JTextArea(sbProductos.toString());
    areaProductos.setEditable(false);
    JScrollPane scrollProductos = new JScrollPane(areaProductos);
    tabbedPane.addTab("Productos", scrollProductos);
    
    // Pestaña de Ventas (texto)
    StringBuilder sbVentas = new StringBuilder();
    sbVentas.append("VENTAS:\n");
    for (Venta v : tienda.getVentas()) 
        sbVentas.append(v.toString()).append("\n");
    JTextArea areaVentas = new JTextArea(sbVentas.toString());
    areaVentas.setEditable(false);
    JScrollPane scrollVentas = new JScrollPane(areaVentas);
    tabbedPane.addTab("Ventas", scrollVentas);
    
    tabbedPane.setPreferredSize(new Dimension(600, 400));
    JOptionPane.showMessageDialog(this, tabbedPane, "Datos del sistema", 
                                JOptionPane.INFORMATION_MESSAGE);
}
     private void inicializarTablaClientes() {
        // Crear el modelo de la tabla con las columnas
        String[] columnNames = {"ID", "NOMBRE", "CEDULA", "TELEFONO"};
        modeloTabla = new DefaultTableModel(columnNames, 0);
        
        // Crear la tabla con el modelo
        tablaClientes = new JTable(modeloTabla);
        
        // Hacer que la tabla no sea editable
        tablaClientes.setEnabled(false);
    }

    // ✅ MÉTODO PARA AGREGAR CLIENTE A LA TABLA
    private void agregarClienteATabla(Cliente cliente) {
        Object[] rowData = {
            cliente.getId(),
            cliente.getNombre(),
            cliente.getCedula(),
            cliente.getTelefono()
        };
        modeloTabla.addRow(rowData);
    }

    // ✅ MÉTODO PARA MOSTRAR LA TABLA EN UN DIALOGO
    private void mostrarTablaEmpleados() {
        JScrollPane scrollPane = new JScrollPane(tablaEmpleados);
        scrollPane.setPreferredSize(new Dimension(500, 300));
        JOptionPane.showMessageDialog(this, scrollPane, "Lista de Empleados", 
                                    JOptionPane.INFORMATION_MESSAGE);
    }
    private void inicializarTablaEmpleados() {
        // Crear el modelo de la tabla con las columnas
        String[] columnNames = {"ID", "NOMBRE", "CEDULA", "TELEFONO","cargo","salario"};
        modeloEmpleados = new DefaultTableModel(columnNames, 0);
        
        // Crear la tabla con el modelo
        tablaEmpleados = new JTable(modeloEmpleados);
        
        // Hacer que la tabla no sea editable
        tablaEmpleados.setEnabled(false);
    }

    // ✅ MÉTODO PARA AGREGAR CLIENTE A LA TABLA
   private void agregarEmpleadoATabla(Empleado empleado) { // ✅ Cambiar a Empleado
    Object[] rowData = {
        empleado.getId(),
        empleado.getNombre(),
        empleado.getCedula(),
        empleado.getTelefono(),
        empleado.getCargo(),    // ✅ Agregar cargo
        empleado.getSalario()   // ✅ Agregar salario
    };
    modeloEmpleados.addRow(rowData);
}

    // ✅ MÉTODO PARA MOSTRAR LA TABLA EN UN DIALOGO
    private void mostrarTablaEmpleado() {
        JScrollPane scrollPane = new JScrollPane(tablaEmpleados);
        scrollPane.setPreferredSize(new Dimension(500, 300));
        JOptionPane.showMessageDialog(this, scrollPane, "Lista de Empleados", 
                                    JOptionPane.INFORMATION_MESSAGE);
    }
      private void cargarDatosExistentesEnTabla(){
    // ✅ CARGAR CLIENTES EXISTENTES
    for (Cliente cliente : ClientRegistry.getClientes()) {
        agregarClienteATabla(cliente);
    }
    
    // ✅ CARGAR EMPLEADOS EXISTENTES
    for (Empleado empleado : tienda.getEmpleados()) {
        agregarEmpleadoATabla(empleado);
    } 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearVenta;
    private javax.swing.JButton MostrarDatos;
    private javax.swing.JButton RegistrarCliente;
    private javax.swing.JButton RegistrarEmpleado;
    private javax.swing.JButton RegistrarProducto;
    // End of variables declaration//GEN-END:variables
}
